name: Enhancement Request
description: Propose a new minor enhancement for the Payara Ecosystem
title: "Enhancement: "
labels: [ "Status: Open", "Type: Enhancement" ]
body:
  - type: textarea
    id: summary
    attributes:
      label: Brief Summary
      description: |
        Describe clearly and concisely a summary of your enhancement request
    validations:
      required: true
  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: |
        Provide a detailed summary of how your proposed enhancement should work
    validations:
      required: true
  - type: textarea
    id: current-outcome
    attributes:
      label: Current Outcome
      description: |
        Explain the drawbacks and disadvantages of the current feature set that is targeted by the proposed enhancement
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Describe any additional details that you think are needed to contextualize your proposed enhancement
  - type: dropdown
    id: ecosystem-tool
    validations:
      required: true
    attributes:
      label: Ecosystem Tool
      description: Which ecosystem tools does this enhancement target?
      multiple: true
      options:
        - Visual Studio IDE Plugin
        - IntelliJ IDEA IDE Plugin
        - Eclipse IDE Plugin
        - Netbeans IDE Plugin
        - Maven Tools
        - Gradle Tools
        - Security Connectors
        - Arquillian Connectors
        - Cloud Connectors
        - Jaeger Tracer
        - Maven Regex Extension