name: Monitor Inactive Open Issues
#Runs every Monday and Thursday at 9:00 A.M
on:
  schedule:
    - cron: "0 9 * * 1,4"
env:
  inactiveIntervalDays: ${{ vars.MONITORING_INACTIVE_INTERVAL_DAYS }}
jobs:
  retrieve-inactive-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      issues: ${{ steps.filter-inactive-issues.outputs.result }}
    steps:
      - name: Check environment
        run: |
          if [ -z $inactiveIntervalDays ]; then
            echo "::error::'MONITORING_INACTIVE_INTERVAL_DAYS' environment variable is not set"
            exit 1
          fi
      - uses: actions/checkout@v3
        if: success()
      - name: Filter inactive issues
        id: filter-inactive-issues
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/scripts/filterInactiveIssues.js');
            return await script({github, context, core});
  notify-inactive-issues:
    runs-on: ubuntu-latest
    needs: retrieve-inactive-issues
    if: ${{ needs.retrieve-inactive-issues.outputs.issues }}
    strategy:
      matrix:
        issues: ${{ fromJSON(needs.retrieve-inactive-issues.outputs.issues) }}
    steps:
      - name: Notify MS Teams channel
        id: notify-ms-teams
        uses: tlolkema/simple-teams-message@main
        with:
          webhook: ${{ secrets.COMMUNITY_EVENTS_WEBHOOK_URL }}
          message_title: Inactive Issue Detected
          message_description: "It's been ${{ env.inactiveIntervalDays }} days since issue number ${{ matrix.issues.number }} has received an update."
          extra_text_blocks: "${{ matrix.issues.assignee }}, please provide an update soon."
