name: Monitor Abandoned Issues
on:
  schedule:
    - cron: "0 */24 * * *"
jobs:
  abandoned-labeler:
    #Needs to be tested (maybe changed to a specific release)
    runs-on: ubuntu-latest
    steps:
      - name: Check for abandoned issues
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const pendingLabel = "Status: Pending";
            const abandonedLabel = "Status: Abandoned";
            
            const timeThreshold = 5 * 60 * 60 * 24 * 1000 // 5 days
            
            // Query all GH issues that are pending and not closed
            const issuesResponse = await github.rest.issues.listForRepo({
              owner,
              repo,
              labels: pendingLabel,
              state: "open",
            });

            for (const issue of issuesResponse.data) {
              const updatedAt = new Date(issue.updated_at).getTime();
              const currentTime = new Date().getTime();
              const updateMessage = `Greetings, 
                It's been more than 5 days since we requested more information or an update from you on the details of this issue. Could you provide an update soon, please?
                We're afraid that if we do not receive an update, we'll have to close this issue due to inactivity.`;

              if (currentTime - updatedAt > timeThreshold) {
                await github.rest.issues.addLabels({
                  owner,
                  repo,
                  issue_number: issue.number,
                  labels: [abandonedLabel],
                });

                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: issue.number,
                  name: pendingLabel,
                });

                await github.rest.issues.createComment({
                  owner,
                  repo,
                  issue_number: issue.number,
                  body: updateMessage,
                });
              }
            }
